#! /usr/bin/env bash

# Execute a git command in every git repository under the current directory
# Copyright (C) 2018  Fin Christensen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

encapsulate() {
    "$@" > \
         >( \
            while read -r line
            do
                echo "    ${line}"
            done
         ) 2> \
         >( \
            while read -r line
            do
                echo "    ${line}"
            done
         )
}

find . -name .git -type d -prune | sed 's;/.git$;;' | while read -r repo
do
    (
        echo -e "\\e[1mGit repository at ${repo}:\\e[0m"
        cd "${repo}" && encapsulate git "$@"
        echo
    )
done
